### ISSUE TITLE
instructions

### ISSUE THREAD

**Issue by sboosali** [mightybyte/reflex-2048#1]
how do i run this?

should i clone it into a reflex-platform project? (if so, i've just run ghcjs --make (no cabal) and edited packages.nix, but i don't get the rest of how relfex-platform works.)

**Comment by mightybyte** [comment]
First run this command:

    deps/reflex-platform/work-on ./packages.nix ./.

Then when that command is finished, you'll be in a nix-shell where you can run:

    cabal configure --ghcjs
    cabal build

I just pushed a new commit with a README that explains this.
